/**
 * Multilingual profanity word list.
 * All entries are lowercase. The filter uses word-boundary regex matching.
 * Organized by language/category.
 */
export const PROFANITY_WORDS: string[] = [
  // ── English ──────────────────────────────────────────
  "fuck", "fucker", "fucking", "fucked", "fucks", "motherfucker", "motherfucking",
  "shit", "shitty", "shitting", "bullshit", "shithead", "dipshit", "horseshit",
  "ass", "asshole", "assholes", "asses", "dumbass", "fatass", "jackass", "smartass", "badass",
  "bitch", "bitches", "bitchy", "bitching", "sonofabitch",
  "cunt", "cunts",
  "dick", "dicks", "dickhead", "dickheads",
  "cock", "cocks", "cocksucker", "cocksucking",
  "pussy", "pussies",
  "damn", "damned", "goddamn", "goddamnit",
  "bastard", "bastards",
  "whore", "whores",
  "slut", "sluts", "slutty",
  "piss", "pissed", "pissing",
  "crap", "crappy",
  "tit", "tits", "titty", "titties",
  "twat", "twats",
  "wanker", "wankers", "wanking",
  "bollocks",
  "bugger",
  "arse", "arsehole",
  "prick", "pricks",
  "nigger", "niggers", "nigga", "niggas",
  "faggot", "faggots", "fag", "fags",
  "retard", "retarded", "retards",
  "spic", "spics",
  "chink", "chinks",
  "kike", "kikes",
  "wetback",
  "beaner",
  "cracker", "crackers",
  "tranny", "trannies",
  "dyke", "dykes",
  "homo", "homos",
  "jizz",
  "cum", "cumshot",
  "dildo", "dildos",
  "blowjob", "blowjobs",
  "handjob",
  "anal",
  "porn", "porno", "pornography",
  "milf",

  // ── English leetspeak / evasion variants ─────────────
  "f*ck", "f**k", "fck", "fuk", "fuq", "phuck", "phuk",
  "sh*t", "sh1t", "sht",
  "a$$", "a**", "@ss", "@sshole",
  "b*tch", "b1tch", "bi+ch",
  "c*nt",
  "d*ck", "d1ck",
  "p*ssy",
  "c0ck",
  "n1gger", "n1gga", "nigg3r",
  "f@g", "f@ggot",
  "r3tard",
  "stfu", "gtfo",

  // ── Spanish ──────────────────────────────────────────
  "puta", "putas", "putada", "hijo de puta", "hijueputa",
  "mierda", "mierdas",
  "coño", "coños",
  "pendejo", "pendejos", "pendeja",
  "cabrón", "cabrones", "cabrona",
  "chingar", "chingada", "chingado", "chinga",
  "verga", "vergudo",
  "culo", "culos",
  "marica", "maricas", "maricón",
  "polla", "pollas",
  "joder", "jodido", "jodida",
  "gilipollas",
  "capullo",
  "hostia", "hostias",
  "cojones",
  "mamón",
  "pinche",
  "culero",
  "gonorrea",
  "malparido", "malparida",

  // ── German ───────────────────────────────────────────
  "scheiße", "scheisse", "scheiss", "scheiß",
  "arschloch", "arschlöcher",
  "fick", "ficken", "ficker", "gefickt",
  "hurensohn", "hurensöhne",
  "hure", "huren",
  "wichser", "wichsen",
  "fotze", "fotzen",
  "schwanz",
  "schwuchtel",
  "missgeburt",
  "drecksau",
  "schlampe", "schlampen",
  "vollidiot",
  "depp",
  "spast", "spasti",
  "bastard",
  "pisser",
  "kacke",
  "leck mich",

  // ── French ───────────────────────────────────────────
  "merde", "merdes", "merdique",
  "putain", "putains",
  "connard", "connards", "connasse", "connasses",
  "enculé", "enculée", "enculer",
  "salaud", "salauds", "salope", "salopes",
  "bordel",
  "foutre", "va te faire foutre",
  "nique", "niquer", "niqué",
  "bâtard",
  "branleur", "branleuse",
  "couilles",
  "bite", "bites",
  "chatte",
  "pédé", "pédés",
  "con", "cons",
  "ta gueule",
  "fils de pute",
  "encule",
  "fdp",
  "ntm",
  "tg",

  // ── Portuguese ───────────────────────────────────────
  "puta", "putas", "filho da puta", "filha da puta",
  "caralho", "caralhos",
  "merda", "merdas",
  "foda", "foder", "foda-se", "fodido", "fodida",
  "cu", "cuzão",
  "buceta",
  "viado", "viados",
  "cacete",
  "porra",
  "desgraçado", "desgraçada",
  "arrombado", "arrombada",
  "corno",
  "piranha",
  "otário", "otária",
  "babaca",
  "pau no cu",
  "vá se fuder",
  "fdp",

  // ── Russian (transliterated) ─────────────────────────
  "blyad", "blyat", "blyadi", "blya",
  "suka", "suki",
  "pizda", "pizdec", "pizdet",
  "khuy", "khui", "hui",
  "nahuy", "nahui", "na hui",
  "yebat", "yob", "yobaniy", "yebanut",
  "mudak", "mudaki",
  "gandon", "gandony",
  "zalupa",
  "pidar", "pidoras", "pidor",
  "debil",
  "idi nahuy", "idi na hui",
  "eblan",
  "shlyukha",
  "tvar",
  "gavno", "govno",
  "zhopa",
  "cyka", "cyka blyat",

  // ── Czech / Slovak ───────────────────────────────────
  "kurva", "kurvy", "do kurvy", "kurva mať",
  "prdel", "do prdele",
  "hovno", "hovná", "hovna",
  "kokot", "kokoti", "kokotina",
  "piča", "píča", "pičo", "píčo", "pico",
  "jebat", "jebať", "jebem", "jebeš", "jebe", "jebnutý", "jebnutej",
  "sráč", "srač",
  "zmrd", "zmrdi", "zmrde",
  "čurák", "čuráci", "curak",
  "debil", "debili", "debilní",
  "hajzl", "hajzle",
  "kretén", "kreténi",
  "vole", "ty vole",
  "pičus", "píčus",
  "zasraný", "zasranej", "zasranec",
  "pojeb", "pojebaný", "pojebanec",
  "zkurvený", "zkurvenej",
  "mrdka", "mrdky",
  "svině", "sviňa",
  "čůrák",
  "ser", "serem", "seru",
  "držka", "drž hubu",
  "kunda", "kundy",
  "somár",
  "prd", "prdy",
  "chcípni",
  "buzerant", "buzeranti",

  // ── Polish ───────────────────────────────────────────
  "kurwa", "kurwy", "kurwica",
  "chuj", "chuje", "chuja",
  "pierdolić", "pierdol", "pierdolę", "pierdolony", "spierdolić", "odpierdol",
  "jebać", "jebany", "jebana", "jebane", "pojebany", "pojebało", "wyjebać", "zajebisty", "zajebiste",
  "dupa", "dupy", "dupek",
  "gówno", "gówna",
  "skurwysyn", "skurwiel",
  "suka", "suki",
  "spierdalaj",
  "kurewstwo",
  "morda",
  "cipa", "cipy",
  "fiut", "fiuta",
  "debil", "debile",
  "dziwka", "dziwki",
  "zjeb",
  "wypierdaj",
  "jebaniec",
  "zajebiście",

  // ── Italian ──────────────────────────────────────────
  "cazzo", "cazzi",
  "merda", "merde",
  "vaffanculo", "fanculo",
  "stronzo", "stronza", "stronzi",
  "minchia",
  "puttana", "puttane",
  "coglione", "coglioni",
  "fica", "figa",
  "troia", "troie",
  "porco dio", "madonna",
  "bastardo", "bastarda",
  "cornuto",
  "porca",
  "cogliona",
  "testa di cazzo",
  "pezzo di merda",
  "rompicoglioni",
  "inculare",

  // ── Dutch ────────────────────────────────────────────
  "kut", "kutwijf",
  "lul", "lullen",
  "kanker", "kankerlijer",
  "godverdomme",
  "tering",
  "tyfus",
  "hoer", "hoeren",
  "klootzak", "klootzakken",
  "mongool",
  "debiel",
  "eikel",
  "opkankeren",
  "kutzooi",
  "neuken",

  // ── Turkish ──────────────────────────────────────────
  "amk", "amına koyayım", "amina koyayim",
  "orospu", "orospu çocuğu", "orospu cocugu",
  "siktir", "siktir git", "siktirgit",
  "yarrak", "yarrак",
  "göt", "götün", "got",
  "piç", "pic",
  "pezevenk",
  "ibne",
  "gavat",
  "bok",
  "haysiyetsiz",
  "kahpe",
  "dangalak",
  "gerizekalı", "gerizekalı",
  "mal",
  "salak",
  "sik",
  "am",

  // ── Arabic (transliterated) ──────────────────────────
  "kuss", "kos", "kos omak", "kos ummak",
  "sharmouta", "sharmota", "sharmuta",
  "ibn el sharmouta",
  "ayre", "ayre fik",
  "zift",
  "khara",
  "tizi",
  "khanith",
  "ibn el kalb",
  "ya kalb",
  "ya hmar",
  "ya khara",
  "kissi",
  "manyak", "manyok",

  // ── Chinese (pinyin) ─────────────────────────────────
  "cao", "cao ni ma",
  "tmd", "ta ma de",
  "sha bi", "shabi",
  "nima", "ni ma",
  "bi", "niubi",
  "diao", "diu",
  "gou ri de",
  "gun", "gun kai",
  "wang ba dan",
  "ma de",
  "si bi",
  "jiba",

  // ── Japanese (romaji) ────────────────────────────────
  "kuso",
  "kisama",
  "temee", "temae",
  "shine",
  "kutabare",
  "baka",
  "aho",
  "manko",
  "chinko", "chinpo",
  "ketsu",
  "fuzakenna",
  "yarou",
  "kichiku",
  "busu",
  "kusottare",

  // ── Korean (romanized) ───────────────────────────────
  "shibal", "sibal", "ssibal",
  "gaesaekki", "gae sae kki",
  "jot", "jotna",
  "byungshin", "byeongsin",
  "michin", "michinom",
  "ssibasaekki",
  "jiral",
  "nom",
  "gaenom",
  "ttolai",
  "babo",
  "jenjang",
  "nimi",
  "sekki",

  // ── Hindi/Urdu (transliterated) ──────────────────────
  "chutiya", "chutiye",
  "madarchod", "mc",
  "behenchod", "bc",
  "bhenchod",
  "gaand", "gand",
  "lund", "lode", "laude",
  "randi", "rande",
  "bhosdike", "bsdk",
  "harami",
  "saala", "saali",
  "kutta", "kutti", "kutiya",
  "tatti",
  "chod", "chodna",

  // ── Hungarian ────────────────────────────────────────
  "bazmeg", "bazd meg",
  "fasz", "faszfej",
  "kurva", "kurvára",
  "geci",
  "szar",
  "segg", "seggfej",
  "picsába", "picsa",
  "köcsög",
  "buzi",
  "rohadt",
  "mocsok",

  // ── Romanian ─────────────────────────────────────────
  "pula", "pule",
  "pizda", "pizdă",
  "muie",
  "fut", "futut", "futu-ți",
  "curva", "curvă",
  "cacat",
  "rahat",
  "bulangiu",
  "nenorocit",
  "idiot",

  // ── Swedish / Norwegian / Danish ─────────────────────
  "fan", "jävla", "jävlar",
  "fitta",
  "kuk",
  "helvete",
  "skit", "skita",
  "hora",
  "knull", "knulla",
  "röv",
  "satans",
];
