-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "cs2Kills" INTEGER;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "cs2Deaths" INTEGER;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "cs2Wins" INTEGER;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "cs2HeadshotPct" DOUBLE PRECISION;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "faceitLevel" INTEGER;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "faceitElo" INTEGER;
